#trigger-4
name: sbr-test
user: mohd-shabbir    # DKube login user name
parameters:
  class: training
  training:
    executor:
      choice: dkube
      buildfromproject: false
      dkube:
        framework:
          choice: tensorflow
          details:
            version: 2.0.0
            image: 'ocdr/dkube-datascience-tf-cpu:v2.0.0-17'
    datums:
      workspace:
        data:
          name: 'mohd-shabbir:mnist'    # <Dkube login name>:<Code repo name>
          version: ''
        script: cat /mnist/README.md
      datasets:
        - name: 'mohd-shabbir:mnist-git'    # <Dkube login name>:<Dataset repo name>
          mountpath: /mnist
          #version: '1681902251300'
      outputs:
        - name: 'mohd-shabbir:mnist'    # <DKube login name>:<Model repo name>
          mountpath: /model
    featuresets: {}
    tags: []
    hyperparams:
      customkv:
        - key: EPOCHS
          value: '1'
      file:
        name: ''
        body: ''
    nworkers: 0
    ngpus: 0
    gpus_override: false
    rdma: false
    hptuning:
      name: ''
      body: ''
  run:
    template: ''
    group: default
